version: '3.8'

services:
  google-scraper-api:
    build: .
    container_name: google-scraper-api
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - scraper-network

  nginx:
    image: nginx:alpine
    container_name: google-scraper-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      google-scraper-api:
        condition: service_healthy
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge

# Optional: Add volume for logs
volumes:
  nginx-logs:
    driver: local